version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu

    steps:
      - checkout

      - run:
          name: Install Sudo
          command: apt-get install sudo
      - run:
          name: Update all Packages
          command: sudo apt-get update
      - run:
          name: Install Php
          command: |
            sudo apt-get install php7.2
            php -v
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run:
          name: Install project dependencies
          command: php composer.phar install
      - run:
          name: Running PHPCS
          command: bash ./.circleci/bin/phpcs.sh
      - run:
          name: Running EsLinting
          command: bash ./.circleci/bin/eslint.sh
      - run:
          name: Running StyleLinting
          command: bash ./.circleci/bin/stylelint.sh
