version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4.6

    steps:
      - checkout

      - run:
          name: Update all Packages
          command: sudo apt-get update
      - run:
          name: Install Composer
          command: |
            curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
      - run:
          name: Install project dependencies
          command: composer install
      - run:
          name: Npm project dependencies
          command: npm install
      - run:
          name: Running PHPCS
          command: bash ./.circleci/bin/phpcs.sh
      - run:
          name: Running EsLinting
          command: bash ./.circleci/bin/eslint.sh
      - run:
          name: Running StyleLinting
          command: bash ./.circleci/bin/stylelint.sh
